#!/usr/bin/env python
import sys
import os
import subprocess

if "BB_MAKEFIFO" in os.environ:
    fifoname = os.environ["BB_MAKEFIFO"]

    r = os.open(fifoname, os.O_RDONLY|os.O_NONBLOCK)
    w = os.open(fifoname, os.O_WRONLY)
    os.close(r)
    r = os.open(fifoname, os.O_RDONLY)

    seen = False
    for i in sys.argv:
        if "-j" in i:
            seen = True
    if seen:
        os.environ["MAKEFLAGS"] = "-j --jobserver-fds=" + str(r) + "," + str(w)

newpath = []
origpath = os.environ["PATH"].split(":")
for p in origpath:
    if "make-intercept" in p:
         continue
    newpath.append(p)
os.environ["PATH"] = ":".join(newpath)

sys.argv[0] = "make"

subprocess.call(sys.argv, shell=False)
